---
niri_kdl_binds_extra:
  Mod+T: 'hotkey-overlay-title="Open a Terminal: kitty" { spawn "kitty"; }'

niri_kdl_binds_skip:
  # no vim keys, please
  - "Mod+H"
  - "Mod+J"
  - "Mod+K"
  - "Mod+L"
  - "Mod+Shift+H"
  - "Mod+Shift+J"
  - "Mod+Shift+K"
  - "Mod+Shift+L"
  - "Mod+Shift+Ctrl+H"
  - "Mod+Shift+Ctrl+J"
  - "Mod+Shift+Ctrl+K"
  - "Mod+Shift+Ctrl+L"

  # PageUp/PagwDown is sufficient, thanks
  - "Mod+U"
  - "Mod+I"
  - "Mod+Ctrl+U"
  - "Mod+Ctrl+I"
  - "Mod+Shift+U"
  - "Mod+Shift+I"
