---
apps_flatpaks:
  - com.obsproject.Studio

apps_packages:
  - brave-browser
  - btop
  - chromium
  - code
  - firefox
  - kitty
  - git
  - vim-default-editor

apps_repos:
  brave-browser:
    description: Brave Browser
    baseurl: https://brave-browser-rpm-release.s3.brave.com/$basearch
    gpgkey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
  code:
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

apps_rpms:
  1password: https://downloads.1password.com/linux/rpm/stable/x86_64/1password-latest.rpm

# add apps_special_tailscale_authkey if you want to start the tailnet
# do not place this in git -- it's a password!
apps_special:
  - joplin
  - tailscale
  - uv
