---
- name: Vars block
  vars:
    configs_opts: "{{ configs_defaults | combine(item.value) }}"
    configs_defaults:
      become: false
      directory: "{{ user_info.home }}/.config/{{ item.key }}"
      files: ["{{ item.key }}.conf"]
  block:
    - name: Create application config file directories
      ansible.builtin.file:
        path: "{{ configs_opts.directory }}"
        state: directory
        mode: "0755"
      become: "{{ configs_opts.become }}"
      loop: "{{ configs_files_final }}"
      when: configs_opts.directory

    - name: Create config files for {{ item.key }}
      ansible.builtin.include_tasks: includes/files.yml
      loop: "{{ configs_files_final }}"
