---
- name: Vars block
  vars:
    rpm_file: "{{ apps_tmpdir.path }}/{{ item }}.rpm"
  when: item not in ansible_facts.packages or apps_upgrade
  block:
    - name: "Download RPM file for {{ item }}"
      ansible.builtin.get_url:
        url: "{{ apps_rpms[item] }}"
        dest: "{{ rpm_file }}"
        mode: "0644"

    - name: "Install RPM for {{ item }}"
      ansible.builtin.command: "dnf install -y {{ rpm_file }}"
      changed_when: true

    # - name: "Install RPM for {{ item }}"
    #   ansible.builtin.dnf:
    #     name: "{{ rpm_file }}"
    #     state: present
