---
- name: Vars block
  vars:
    rpm_file: "{{ apps_tmpdir.path }}/{{ item.key }}.rpm"
  when: item.key not in ansible_facts.packages or apps_upgrade
  block:
    - name: "Download RPM file for {{ item.key }}"
      ansible.builtin.get_url:
        url: "{{ item.value }}"
        dest: "{{ rpm_file }}"
        mode: "0644"

    - name: "Install RPM for {{ item.key }}"
      ansible.builtin.command: "dnf install -y {{ rpm_file }}"
      changed_when: true

    # - name: "Install RPM for {{ item.key }}"
    #   ansible.builtin.dnf:
    #     name: "{{ rpm_file }}"
    #     state: present
