---
- name: Copy config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ niri_user.home }}/.config/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  loop: "{{ niri_config_files }}"
