---
- name: Create user systemd directory
  ansible.builtin.file:
    state: directory
    dest: "{{ user_info.home }}/.config/systemd/user"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Template systemd service files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ user_info.home }}/.config/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: systemd_user_daemon_reload
  loop: "{{ niri_systemd_service_templates }}"

- name: Add niri.service wants # noqa: command-instead-of-module
  ansible.builtin.command:
    cmd: "systemctl --user add-wants niri.service {{ item }}"
    creates: "{{ user_info.home }}/.config/systemd/user/niri.service.wants/{{ item }}"
  loop: "{{ niri_service_wants }}"
