---
- name: Create niri config directory
  ansible.builtin.file:
    state: directory
    dest: "{{ user_info.home }}/.config/niri"
    mode: "0755"

- name: Template niri config
  ansible.builtin.template:
    src: "config.kdl.j2"
    dest: "{{ user_info.home }}/.config/niri/config.kdl"
    mode: "0644"
    backup: true
