---
all:
  children:
    debian:
      hosts:
        beelink:
        pangolin:
        yoga:
    fedora:
      children:
        fedora_amd64:
          hosts:
        fedora_arm64:
          hosts:
            asahi:
    niri:
      hosts:
        asahi:
    macos:
      hosts:
        macbook:

  hosts:
    asahi:
    beelink:
    docker:
      ansible_host: host.docker.internal
    htpc:
    macbook:
      ansible_host: host.docker.internal
    pangolin:
    pve:
    yoga:

  vars:
    ansible_user: jdratlif
