---
- name: Install flatpak
  ansible.builtin.package:
    name: flatpak
    state: present
  become: true

- name: Install flathub remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpak apps
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ apps_flatpaks_final }}"
