---
# add extra flatpaks, removing apps_skip, and sort the result
apps_flatpaks_final: |
  {{
    apps_flatpaks
    | union(apps_flatpaks_extra)
    | difference(apps_skip)
    | sort
  }}

apps_packages_final: |
  {{
    apps_packages
    | union(apps_packages_extra)
    | difference(apps_skip)
    | sort
  }}

apps_repos_final: |
  {{
    apps_repos
    | combine(apps_repos_extra)
    | dict2items
    | rejectattr('key', 'in', apps_skip)
    | selectattr('key', 'in', apps_packages_final)
    | sort(attribute='key')
  }}

apps_rpms_final: |
  {{
    apps_rpms
    | combine(apps_rpms_extra)
    | dict2items
    | rejectattr('key', 'in', apps_skip)
    | sort(attribute='key')
  }}

apps_special_final: |
  {{
    apps_special
    | union(apps_special_extra)
    | difference(apps_skip)
    | sort
  }}
