---
niri_config_dirs:
  - niri
  - waybar

niri_config_files:
  - niri/config.kdl
  - waybar/config.jsonc
  - waybar/style.css

niri_packages:
  - niri
  - blueman
  - mate-polkit
  - network-manager-applet
  - pasystray
  - sddm
  - sddm-themes

niri_service_wants:
  - waybar.service
  - mate-polkit.service
  - swaybg.service
  - swayidle.service

niri_systemd_service_templates:
  - systemd/user/mate-polkit.service
  - systemd/user/swaybg.service
  - systemd/user/swayidle.service
