---
apps_flatpaks:
  - org.videolan.VLC

apps_packages:
  - acl
  - bind-utils
  - brave-browser
  - btop
  - cascadia-fonts-all
  - chromium
  - cifs-utils
  - evolution-ews
  - firefox
  - freerdp
  - git
  - gnome-calculator
  - kitty
  - opensc
  - openssl
  - podman-compose
  - podman-docker
  - terminus-fonts-console
  - vim-default-editor

apps_repos:
  brave-browser: https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo

# add apps_special_tailscale_authkey if you want to start the tailnet
# do not place this in git -- it's a password!
apps_special:
  - tailscale
  - uv
