---
swaylock_options_final: |
  {{
    (
      swaylock_options
      | combine(swaylock_options_extra)
    )
    | dict2items
    | rejectattr('key', 'in', swaylock_options_skip)
    | sort(attribute='key')
  }}
