---
ssh_authorized_keys_final: |
  {{
    ssh_authorized_keys
    | union(ssh_authorized_keys_extra)
    | difference(ssh_authorized_keys_skip)
    | sort
  }}

ssh_common_options_final: |
  {{
    ssh_common_options
    | combine(ssh_common_options_extra)
    | dict2items
    | rejectattr('key', 'in', ssh_common_options_skip)
    | sort(attribute='key')
    | items2dict
  }}

ssh_config_templates: [config, authorized_keys]

ssh_pkcs11_lib:
  Darwin: /usr/lib/ssh-keychain.dylib
  Debian: /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so
  RedHat: /usr/lib64/pkcs11/opensc-pkcs11.so
  Windows: "C:\\Program Files\\OpenSC Project\\OpenSC\\pkcs11\\opensc-pkcs11.dll"

ssh_identity_keys_final: |
  {{
    ssh_identity_keys
    | combine(ssh_identity_keys_extra)
    | dict2items
    | rejectattr('key', 'in', ssh_identity_keys_skip)
    | sort(attribute='key')
  }}
