---
- name: Template bash config files
  ansible.builtin.template:
    src: "{{ item }}.sh.j2"
    dest: "{{ user_info.home }}/.{{ item }}"
    backup: true
    mode: "0644"
  loop: "{{ bash_templates }}"
