---
argument_specs:
  main:
    options:
      swayidle_events:
        type: dict
        description: Which events to handle with swayidle
        options:
          after-resume:
            type: str
            description: Commands to run after system resumes from sleep
          before-sleep:
            type: str
            default: swaylock -f
            description: Commands to run before system goes to sleep
          idlehint:
            type: int
            description: Set IdleHint timeout
          lock:
            type: str
            description: Command to run when logind is locked
          unlock:
            type: str
            description: Command to run when logind is unlocked
      swayidle_timeout_monitors:
        type: int
        default: 601
        description: Timeout to turn the monitors off in seconds
      swayidle_timeout_screenlock:
        type: int
        default: 600
        description: Timeout to lock the screen in seconds
      swayidle_timeouts:
        type: list
        default:
          - seconds: "{{ swayidle_timeout_screenlock }}"
            command: swaylock -f
          - seconds: "{{ swayidle_timeout_monitors }}"
            command: niri msg action power-off-monitors
        description: Sway idle timeout arguments
        elements: dict
        options:
          seconds:
            type: int
            required: true
            description: Number of seconds for the timeout event
          command:
            type: str
            required: true
            description: Command to run when timeout is triggered
          resume:
            type: str
            description: Command to run after activity post timeout

dependencies:
  - role: sysengquick.unix.user_systemd_folder
